#!/usr/bin/env python3

import sys
from lox import Lox

plox = Lox()

if len(sys.argv) > 2:
    print("Usage: plox [file]")
elif len(sys.argv) == 2:
    plox.run_file(sys.argv[1])
else:
    plox.run_interactive()
