#!/usr/bin/env python3

import sys

from lox import Lox

if __name__ == "__main__":
    argv = sys.argv[1:]
    lox = Lox()

    if len(argv) > 1:
        print("Usage: plox [script]")
    elif len(argv) == 1:
        lox.run_file(argv[0])
    else:
        lox.run_interactive()
